---
language: python
python: "2.7"
services:
  - docker
sudo: required

addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible molecule and docker
  - pip install ansible molecule docker-py

  # Check ansible version
  - ansible --version

  # Check molecule version
  - molecule --version

script:
  - molecule test

branches:
  only:
    - master

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
