---
# tasks file for haproxy

- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Configure rsyslog for HAProxy logs
  template:
    src: haproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
  notify: restart rsyslog

- name: Enable HAProxy service
  service:
    name: haproxy
    state: started
    enabled: True
